name: Linters

on: [push, pull_request]

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus at-spi2-core

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Check for idiomatic code
        run: cargo clippy --all --all-features -- -D warnings
